services:
  pds-database:
    image: postgres:14-alpine
    container_name: pds-database
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6255:5432'
    expose:
      - 6255
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
      - ${PWD}/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pds-database-data:/var/lib/postgresql/data
volumes:
  pds-database-data:
