spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6255/pds}
  flyway:
    schemas: pds

server:
  port: 8080
management:
  server:
    port: 7979
  endpoints:
    web:
      exposure:
        include: health
      base-path: "/actuator"
  endpoint:
    health:
      probes:
        enabled: true
